M48
; DRILL file {KiCad (7.0.0)} date Mon Nov 20 19:32:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-20T19:32:13-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1339
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.8419Y-2.847
X6.1522Y-2.847
T2
X5.5Y-2.8297
X6.5Y-2.8297
T0
M30
