M48
; DRILL file {KiCad (6.0.7)} date Tue Sep 20 18:48:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-20T18:48:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X5.7323Y-3.6179
X5.8323Y-3.6179
X5.9323Y-3.6179
T2
X5.8268Y-3.3031
T0
M30
